# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: geckos3

before:
  hooks:
    - go mod tidy
    - go test -count=1 ./...

builds:
  - id: geckos3
    binary: geckos3
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: geckos3
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Security Updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: randilt
    name: geckos3
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## geckos3 {{ .Tag }} ({{ .Date }})

    Lightweight S3-compatible object storage server

    ### Installation

    Download the archive for your platform, extract it, and run:
    ```bash
    ./geckos3
    ```

    Or use Docker:
    ```bash
    docker pull ghcr.io/randilt/geckos3:{{ .Tag }}
    ```
  footer: |
    **Full Changelog**: https://github.com/randilt/geckos3/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    Released with [GoReleaser](https://goreleaser.com)
